# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy to closed testing track"
  
  lane :closed_testing do
    # changelog = prompt(text: "Changelog: ")
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "alpha", # Options: 'internal', 'alpha', 'beta', 'production'
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      release_status: "completed",
      skip_upload_apk: true
    )
  end

end
